apiVersion: apps/v1
kind: Deployment
metadata:
  name: mistify-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mistify-backend
  template:
    metadata:
      labels:
        app: mistify-backend
    spec:
      containers:
        - name: mistify-backend
          image: el24ss/mistify-backend:latest
          env:
            - name: MONGO_URL
              value: "mongodb://root:password@10.10.3.15:27017" ##TODOO ou secrets
          ports:
            - containerPort: 3000